apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attendancedb-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: attendancedb
  labels:
    app: attendancedb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: attendancedb
  template:
    metadata:
      labels:
        app: attendancedb
    spec:
      containers:
      - name: attendancedb
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "root"
        - name: MYSQL_DATABASE
          value: "attendancedb"
        volumeMounts:
        - name: attendancedb-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: attendancedb-storage
        persistentVolumeClaim:
          claimName: attendancedb-pvc